export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.jsx",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-dim": "#d8dadc",
              "inverse-primary": "#b6c4ff",
              "inverse-on-surface": "#eff1f3",
              "on-tertiary-fixed-variant": "#3f465c",
              "on-secondary-container": "#6f5100",
              "secondary-fixed-dim": "#f9bd22",
              "on-error-container": "#93000a",
              "surface-container": "#eceef0",
              "on-surface": "#191c1e",
              "on-secondary-fixed-variant": "#5c4300",
              "on-tertiary-container": "#a4acc5",
              "secondary-fixed": "#ffdf9f",
              "outline-variant": "#c5c5d3",
              "surface-container-low": "#f2f4f6",
              "secondary-container": "#ffc329",
              "on-primary-container": "#90a8ff",
              "on-tertiary": "#ffffff",
              "on-secondary": "#ffffff",
              "surface-bright": "#f7f9fb",
              "primary": "#00236f",
              "on-background": "#191c1e",
              "on-primary-fixed-variant": "#264191",
              "tertiary": "#222a3e",
              "surface-tint": "#4059aa",
              "surface": "#f7f9fb",
              "primary-fixed": "#dce1ff",
              "outline": "#757682",
              "primary-container": "#1e3a8a",
              "surface-container-highest": "#e0e3e5",
              "surface-variant": "#e0e3e5",
              "tertiary-container": "#384055",
              "error-container": "#ffdad6",
              "secondary": "#795900",
              "on-primary-fixed": "#00164e",
              "primary-fixed-dim": "#b6c4ff",
              "on-primary": "#ffffff",
              "surface-container-high": "#e6e8ea",
              "on-secondary-fixed": "#261a00",
              "tertiary-fixed": "#dae2fd",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed": "#131b2e",
              "tertiary-fixed-dim": "#bec6e0",
              "on-surface-variant": "#444651",
              "inverse-surface": "#2d3133",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "background": "#f7f9fb"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "stack-sm": "8px",
              "stack-lg": "32px",
              "margin-desktop": "32px",
              "sidebar-width": "280px",
              "margin-mobile": "16px",
              "container-max": "1280px",
              "stack-md": "16px",
              "gutter": "24px"
      },
      "fontFamily": {
              "code": ["Inter"],
              "label-md": ["Inter"],
              "display-lg": ["Inter"],
              "body-sm": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "body-md": ["Inter"],
              "body-lg": ["Inter"],
              "headline-md": ["Inter"],
              "headline-lg": ["Inter"]
      },
      "fontSize": {
              "code": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
              "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
              "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
